#apiVersion: v1
#kind: Namespace
#metadata:
  #name: abdemo
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccop-ab-demo
  namespace: abdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ccop-ab-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ccop-ab-demo
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ccop-ab-demo
        image: ccopakssandboxacrimages.azurecr.io/abclusterdemo/cluster02:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
        - name: abdemo
---
apiVersion: v1
kind: Service
metadata:
  name: ccop-ab-demo-svc
  namespace: abdemo
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ccop-ab-demo
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ccop-ab-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: abdemo
spec:
   rules:
   - http:
      paths:
      - backend:
          serviceName: ccop-ab-demo-svc
          servicePort: 80
        path: /
